#!/usr/bin/env bash

./main.mjs 'rāmaḥ asti'
./main.mjs 'devaḥ icchati'
./main.mjs 'guruḥ upadeśa'
./main.mjs 'rāmaḥ paśyati'
./main.mjs 'devaḥ karoti'
./main.mjs 'rāmaḥ śāstra'
./main.mjs 'guruḥ satyam'
./main.mjs 'rāma asti'
./main.mjs 'devi īśa'
./main.mjs 'guru upadeśa'
./main.mjs 'rāma indra'
./main.mjs 'deva upadeśa'
./main.mjs 'rāma ēva'
./main.mjs 'deva ōjas'
./main.mjs 'hari asti'
./main.mjs 'guru ātmā'
./main.mjs 'tat śiva'
./main.mjs 'manas indra'
./main.mjs 'saṁ gacchati'
./main.mjs 'saṁ tat cit'
./main.mjs 'rāmas ca'
./main.mjs 'sad dharma'
./main.mjs 'tat satyam'
./main.mjs 'rājan candra'
./main.mjs 'devas kāma'
./main.mjs 'saṁskāra'
./main.mjs 'saṁpūrṇa'
./main.mjs 'rāmaḥ'
./main.mjs 'ḥ asti'
./main.mjs 'a'
./main.mjs 'rāma'
./main.mjs 'rāmaḥ xyz'
./main.mjs 'abc ḥ'
./main.mjs 'te ē'
./main.mjs 'yo ō'
./main.mjs 'aḥ aḥ'
./main.mjs 'ṁ'
./main.mjs 'ṁ k'
./main.mjs 'k ṁ'
